#!/usr/bin/env python

import argparse
import hospital.gui.officials as officials
import subprocess
import sys


parser = argparse.ArgumentParser(
    prog="Hospital Management System",
    description="",
    allow_abbrev=False,
)

parser.add_argument(
    "-u",
    "--user",
    action="store",
    required=True,
    default="official",
    help="Specify the user. Accepted values are official or manager.",
)

args = parser.parse_args()
user = args.user

if user == "official":
    window = officials.ApplicationWindow()
    window.mainloop()
elif user == "manager":
    subprocess.run('python ' + sys.path[0]+'/gui/managers.py', shell=True)
else:
    raise ValueError("User must either be manager or official.")
